/*
	Staging Script for Miscellaneous items

	Note: These scripts are created and for the usage in modpacks curated by Team 8Bit. 
    You can use these scripts for reference and for learning but not for copying and 
    pasting and claiming as your own
*/

import crafttweaker.data.IData;
import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
import crafttweaker.liquid.ILiquidStack;
import mods.zenstages.Stage;
import mods.zenstages.ZenStager;

//Liquids
mods.ItemStages.stageLiquid("overworld", <liquid:refined_life_essence>);
mods.ItemStages.stageLiquid("overworld", <liquid:refined_life_essence>);
mods.ItemStages.stageLiquid("overworld", <liquid:lifeessence>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_residue>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_residue_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_residue_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_heavy>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_heavy_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_heavy_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_dense>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_dense_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_dense_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_distilled>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_distilled_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:oil_distilled_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_dense>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_dense_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_dense_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_mixed_heavy>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_mixed_heavy_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_mixed_heavy_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_light>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_light_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_light_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_mixed_light>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_mixed_light_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_mixed_light_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_gaseous>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_gaseous_heat_1>);
mods.ItemStages.stageLiquid("overworld", <liquid:fuel_gaseous_heat_2>);
mods.ItemStages.stageLiquid("overworld", <liquid:plantoil>);
mods.ItemStages.stageLiquid("overworld", <liquid:biodiesel>);
mods.ItemStages.stageLiquid("overworld", <liquid:concrete>);
mods.ItemStages.stageLiquid("overworld", <liquid:diesel>);
mods.ItemStages.stageLiquid("overworld", <liquid:lubricant>);
mods.ItemStages.stageLiquid("overworld", <liquid:napalm>);
mods.ItemStages.stageLiquid("overworld", <liquid:dist_water>);
mods.ItemStages.stageLiquid("overworld", <liquid:experience>);
mods.ItemStages.stageLiquid("overworld", <liquid:potion>);
mods.ItemStages.stageLiquid("overworld", <liquid:potion_splash>);
mods.ItemStages.stageLiquid("overworld", <liquid:potion_lingering>);
mods.ItemStages.stageLiquid("overworld", <liquid:mushroom_stew>);
mods.ItemStages.stageLiquid("overworld", <liquid:refined_biofuel>);
mods.ItemStages.stageLiquid("overworld", <liquid:biocrude>);
mods.ItemStages.stageLiquid("overworld", <liquid:seed_oil>);
mods.ItemStages.stageLiquid("overworld", <liquid:tree_oil>);
mods.ItemStages.stageLiquid("overworld", <liquid:resin>);
mods.ItemStages.stageLiquid("overworld", <liquid:syrup>);
mods.ItemStages.stageLiquid("overworld", <liquid:sap>);
mods.ItemStages.stageLiquid("overworld", <liquid:refined_fuel>);
mods.ItemStages.stageLiquid("overworld", <liquid:refined_oil>);
mods.ItemStages.stageLiquid("overworld", <liquid:coal>);
mods.ItemStages.stageLiquid("overworld", <liquid:creosote>);

mods.ItemStages.stageLiquid("nonstacked", <liquid:astralsorcery.liquidstarlight>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:nutrient_distillation>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:ender_distillation>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:vapor_of_levity>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hootch>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:rocket_fuel>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:fire_water>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:xpjuice>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:liquid_sunshine>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:cloud_seed>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:cloud_seed_concentrated>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:anti_venom>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:beetle_juice>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:ethanol>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:essence>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:meat>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:latex>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:sewage>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:sludge>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:biofuel>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:if.pink_slime>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:if.protein>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:if.ore_fluid_raw>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:if.ore_fluid_fermented>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:brine>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:liquidlithium>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heavywater>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:thorium>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:uranium>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:uranium_233>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:uranium_235>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:uranium_238>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:neptunium_236>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:neptunium_237>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:plutonium_238>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:plutonium_239>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:plutonium_241>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:plutonium_242>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:americium_241>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:americium_242>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:americium_243>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:curium_243>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:curium_245>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:curium_246>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:curium_247>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:berkelium_247>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:berkelium_248>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:californium_249>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:californium_250>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:californium_251>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:californium_252>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:tbu>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:tbu_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:tbu_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leu_233>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leu_233_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leu_233_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heu_233>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heu_233_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heu_233_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leu_235>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leu_235_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leu_235_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heu_235>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heu_235_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heu_235_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:len_236>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:len_236_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:len_236_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hen_236>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hen_236_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hen_236_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lep_239>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lep_239_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lep_239_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hep_239>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hep_239_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hep_239_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lep_241>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lep_241_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lep_241_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hep_241>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hep_241_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hep_241_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:mix_239>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:mix_239_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:mix_239_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:mix_241>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:mix_241_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:mix_241_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lea_242>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lea_242_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lea_242_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hea_242>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hea_242_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hea_242_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_243>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_243_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_243_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_243>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_243_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_243_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_245>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_245_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_245_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_245>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_245_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_245_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_247>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_247_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecm_247_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_247>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_247_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecm_247_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leb_248>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leb_248_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:leb_248_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heb_248>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heb_248_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:heb_248_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecf_249>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecf_249_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecf_249_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecf_249>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecf_249_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecf_249_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecf_251>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecf_251_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lecf_251_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecf_251>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecf_251_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:hecf_251_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_tbu>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_tbu_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_tbu_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leu_233>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leu_233_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leu_233_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heu_233>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heu_233_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heu_233_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leu_235>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leu_235_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leu_235_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heu_235>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heu_235_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heu_235_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_len_236>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_len_236_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_len_236_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hen_236>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hen_236_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hen_236_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lep_239>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lep_239_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lep_239_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hep_239>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hep_239_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hep_239_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lep_241>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lep_241_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lep_241_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hep_241>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hep_241_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hep_241_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_mix_239>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_mix_239_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_mix_239_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_mix_241>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_mix_241_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_mix_241_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lea_242>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lea_242_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lea_242_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hea_242>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hea_242_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hea_242_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_243>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_243_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_243_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_243>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_243_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_243_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_245>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_245_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_245_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_245>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_245_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_245_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_247>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_247_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecm_247_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_247>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_247_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecm_247_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leb_248>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leb_248_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_leb_248_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heb_248>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heb_248_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_heb_248_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecf_249>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecf_249_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecf_249_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecf_249>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecf_249_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecf_249_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecf_251>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecf_251_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_lecf_251_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecf_251>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecf_251_fluoride>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:depleted_hecf_251_fluoride_flibe>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:iron>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:iron_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:iron_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:redstone_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:redstone_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:quartz>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:quartz_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:quartz_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:obsidian>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:obsidian_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:obsidian_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:nether_brick>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:nether_brick_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:nether_brick_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:glowstone_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:glowstone_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lapis>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lapis_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lapis_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:gold>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:gold_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:gold_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:prismarine>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:prismarine_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:prismarine_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:slime>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:slime_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:slime_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:end_stone>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:end_stone_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:end_stone_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:purpur>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:purpur_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:purpur_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:diamond>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:diamond_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:diamond_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:emerald>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:emerald_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:emerald_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:copper>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:copper_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:copper_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:tin>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:tin_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:tin_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lead>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lead_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lead_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:boron>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:boron_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:boron_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lithium>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lithium_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:lithium_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:magnesium>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:magnesium_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:magnesium_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:manganese>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:manganese_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:manganese_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:aluminum>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:aluminum_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:aluminum_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:silver>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:silver_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:silver_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:fluorite>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:fluorite_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:fluorite_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:villiaumite>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:villiaumite_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:villiaumite_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:carobbiite>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:carobbiite_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:carobbiite_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:arsenic_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:arsenic_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:liquid_nitrogen_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:liquid_nitrogen_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:liquid_helium_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:liquid_helium_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:enderium_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:enderium_nak_hot>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:cryotheum_nak>);
mods.ItemStages.stageLiquid("nonstacked", <liquid:cryotheum_nak_hot>);


//Items
/* mods.ItemStages.addItemStage("overworld", <mekanism:machineblock2:11>); //Fluid Tank */

mods.ItemStages.addItemStage("overworld", <minecraft:chest>);
mods.ItemStages.addItemStage("overworld", <minecraft:furnace>);
mods.ItemStages.addItemStage("overworld", <contenttweaker:material_part:*>);
mods.ItemStages.addItemStage("overworld", <contenttweaker:sub_block_holder_0:*>);
mods.ItemStages.addItemStage("overworld", <contenttweaker:sub_block_holder_1:*>);
mods.ItemStages.addItemStage("overworld", <contenttweaker:sub_block_holder_2:*>);
mods.ItemStages.addItemStage("overworld", <contenttweaker:sub_block_holder_3:*>);
mods.ItemStages.addItemStage("overworld", <contenttweaker:sub_block_holder_4:*>);
mods.ItemStages.addItemStage("overworld", <contenttweaker:sub_block_holder_5:*>);
mods.ItemStages.addItemStage("overworld", <contenttweaker:sub_block_holder_6:*>);

mods.ItemStages.addItemStage("overworld", <patchouli:guide_book>.withTag({"patchouli:book": "alchemistry:alchemistry_book"}));
mods.ItemStages.addItemStage("overworld", <animalcrops:seeds>.withTag({entity: "minecraft:ghast"}));
mods.ItemStages.addItemStage("overworld", <animalcrops:seeds>.withTag({entity: "minecraft:wither_skeleton"}));
mods.ItemStages.addItemStage("overworld", <animalcrops:seeds>.withTag({entity: "minecraft:magma_cube"}));
mods.ItemStages.addItemStage("overworld", <animalcrops:seeds>.withTag({entity: "minecraft:blaze"}));
mods.ItemStages.addItemStage("overworld", <animalcrops:seeds>.withTag({entity: "thermalfoundation:basalz"}));
mods.ItemStages.addItemStage("overworld", <animalcrops:seeds>.withTag({entity: "thermalfoundation:blitz"}));
mods.ItemStages.addItemStage("overworld", <animalcrops:seeds>.withTag({entity: "thermalfoundation:blizz"}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 58 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 59 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 59 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 59 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 59 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 59 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 60 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 60 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 60 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 60 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 60 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 65 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 65 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 65 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 65 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 5 as short, id: 65 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 1 as short, id: 66 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 66 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 66 as short}]}));
mods.ItemStages.addItemStage("overworld", <base:wrench>);
mods.ItemStages.addItemStage("overworld", <baubles:ring>);
mods.ItemStages.addItemStage("overworld", <guideapi:bloodarsenal-guide>);
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.health"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 0, key: "bloodmagic.upgrade.stepAssist"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 0, key: "bloodmagic.upgrade.elytra"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.arrowShot"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.stormTrooper"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.selfSacrifice"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.fireResist"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.sprintAttack"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.physicalProtect"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 0, key: "bloodmagic.upgrade.crippledArm"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.solarPowered"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.movement"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.knockback"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 0, key: "bloodmagic.upgrade.quenched"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 0, key: "bloodmagic.upgrade.repair"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.jump"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.experienced"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.slowness"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.slowHeal"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.nightSight"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.fallProtect"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.digSlowdown"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 0, key: "bloodmagic.upgrade.slippery"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.meleeDamage"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.criticalStrike"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.digging"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.battleHunger"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 4, key: "bloodmagic.upgrade.poisonResist"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.grimReaper"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.graveDigger"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.meleeDecrease"}));
mods.ItemStages.addItemStage("overworld", <bloodmagic:upgrade_tome>.withTag({level: 9, key: "bloodmagic.upgrade.disoriented"}));
mods.ItemStages.addItemStage("overworld", <guideapi:bloodmagic-guide>);
mods.ItemStages.addItemStage("overworld", <buildcraftlib:guide>.withTag({BookName: "buildcraftlib:meta"}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:laser>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:assembly_table>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:integration_table>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:redstone_chipset>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:redstone_chipset:1>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:redstone_chipset:2>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:redstone_chipset:3>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:redstone_chipset:4>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 1 as byte, modifier: 0 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 1 as byte, modifier: 1 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 1 as byte, modifier: 2 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 1 as byte, modifier: 3 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 1 as byte, modifier: 0 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 1 as byte, modifier: 1 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 1 as byte, modifier: 2 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 1 as byte, modifier: 3 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 2 as byte, modifier: 0 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 2 as byte, modifier: 1 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 2 as byte, modifier: 2 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 2 as byte, modifier: 3 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 2 as byte, modifier: 0 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 2 as byte, modifier: 1 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 2 as byte, modifier: 2 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 2 as byte, modifier: 3 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 3 as byte, modifier: 0 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 3 as byte, modifier: 1 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 3 as byte, modifier: 2 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 3 as byte, modifier: 3 as byte, logic: 0 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 3 as byte, modifier: 0 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 3 as byte, modifier: 1 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 3 as byte, modifier: 2 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_gate>.withTag({gate: {material: 3 as byte, modifier: 3 as byte, logic: 1 as byte}}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:1>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:2>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:3>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:4>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:5>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:6>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:7>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:8>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:9>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:10>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:11>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:12>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:13>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:14>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:15>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:16>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:17>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:18>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:19>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:20>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:21>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:22>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:23>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:24>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:25>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:26>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:27>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:28>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:29>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:30>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:31>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:32>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_lens:33>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_pulsar>);
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:plug_light_sensor>);
mods.ItemStages.addItemStage("overworld", <compactstorage:chestbuilder>);
mods.ItemStages.addItemStage("overworld", <compactstorage:barrel>);
mods.ItemStages.addItemStage("overworld", <compactstorage:barrel_fluid>);
mods.ItemStages.addItemStage("overworld", <lumberjack:iron_lumberaxe>);
mods.ItemStages.addItemStage("overworld", <lumberjack:diamond_lumberaxe>);
mods.ItemStages.addItemStage("overworld", <lumberjack:gold_lumberaxe>);
mods.ItemStages.addItemStage("overworld", <randomthings:spectrecoil_number>);
mods.ItemStages.addItemStage("overworld", <immersiveengineering:shader>.withTag({shader_name: "Terra"}));
mods.ItemStages.addItemStage("overworld", <immersiveengineering:shader_bag>.withTag({rarity: "RARE"}));
mods.ItemStages.addItemStage("overworld", <immersiveengineering:shader_bag>.withTag({rarity: "EPIC"}));
mods.ItemStages.addItemStage("overworld", <immersiveengineering:shader_bag>.withTag({rarity: "RELIC"}));
mods.ItemStages.addItemStage("overworld", <immersiveengineering:shader_bag>.withTag({rarity: "IE:MASTERWORK"}));
mods.ItemStages.addItemStage("overworld", <ftbquests:screen>);
mods.ItemStages.addItemStage("overworld", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 1 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 2 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 3 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:screen>.withTag({BlockEntityTag: {Size: 4 as byte, id: "ftbquests:screen_core"}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:progress_detector>);
mods.ItemStages.addItemStage("overworld", <ftbquests:detector>);
mods.ItemStages.addItemStage("overworld", <ftbquests:detector:1>);
mods.ItemStages.addItemStage("overworld", <ftbquests:progress_screen>);
mods.ItemStages.addItemStage("overworld", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 2 as byte, id: "ftbquests:progress_screen_core", Width: 1 as byte}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 4 as byte, id: "ftbquests:progress_screen_core", Width: 2 as byte}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 6 as byte, id: "ftbquests:progress_screen_core", Width: 3 as byte}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 8 as byte, id: "ftbquests:progress_screen_core", Width: 4 as byte}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:progress_screen>.withTag({BlockEntityTag: {Height: 3 as byte, id: "ftbquests:progress_screen_core", Width: 2 as byte}, display: {Lore: ["(+NBT)"]}}));
mods.ItemStages.addItemStage("overworld", <ftbquests:chest>);
mods.ItemStages.addItemStage("overworld", <ftbquests:custom_icon>.withTag({icon: "ftblib:textures/icons/support.png"}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "stagnium", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "redwheat", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "brown_mushroom", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "dandelion", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "terra_wart", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "venomilia", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "beetroots", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "potato", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "nether_wart", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "eatingplant", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "blackthorn", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "weed", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "carrots", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "ferru", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "melon", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "stickreed", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "plumbiscus", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "aurelia", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "cyprium", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "tulip", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "cocoa", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "cyazint", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "coffee", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "red_mushroom", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "shining", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "rose", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "hops", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <ic2:crop_seed_bag>.withTag({owner: "ic2", scan: 4 as byte, growth: 1 as byte, id: "pumpkin", resistance: 1 as byte, gain: 1 as byte}));
mods.ItemStages.addItemStage("overworld", <buildcraftsilicon:advanced_crafting_table>);
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 25 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 25 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 25 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 2 as short, id: 13 as short}]}));
mods.ItemStages.addItemStage("overworld", <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 3 as short, id: 13 as short}]}));







mods.ItemStages.addItemStage("nonstacked", <astralsorcery:blockfaketree>);
mods.ItemStages.addItemStage("nonstacked", <astralsorcery:blockportalnode>);
mods.ItemStages.addItemStage("nonstacked", <actuallyadditions:block_inputter>);
mods.ItemStages.addItemStage("nonstacked", <actuallyadditions:block_inputter_advanced>);
mods.ItemStages.addItemStage("nonstacked", <patchouli:guide_book>.withTag({"patchouli:book": "deepmoblearning:book"}));
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:1>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:2>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:3>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:4>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:5>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:6>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:7>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:8>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:9>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:10>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:11>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:12>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:13>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:14>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:15>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:16>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:17>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:18>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:19>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:20>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:21>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:22>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:23>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:24>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:25>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:26>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:27>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:28>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:29>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:30>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:31>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:32>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:33>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:34>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:35>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:36>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:37>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:38>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:39>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:40>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:41>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:42>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:44>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:46>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:45>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:47>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:48>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:49>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:50>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:51>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:52>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:53>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:54>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:55>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:56>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:57>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:58>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:59>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:60>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:61>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:62>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:63>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:64>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:65>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:66>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:67>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:73>);
mods.ItemStages.addItemStage("nonstacked", <erebus:materials:74>);
mods.ItemStages.addItemStage("nonstacked", <opencomputers:card:5>);
mods.ItemStages.addItemStage("nonstacked", <opencomputers:storage:1>.withTag({"oc:data": {}}));
mods.ItemStages.addItemStage("nonstacked", <oeintegration:excavatemodifier>);
mods.ItemStages.addItemStage("nonstacked", <patchouli:guide_book>.withTag({"patchouli:book": "pneumaticcraft:book"}));